### ISSUE TITLE
Use php-parser v4

### ISSUE THREAD

**Issue by redthor** [Ocramius/GeneratedHydrator#79]
I just ran into #69 but with [nikic/php-parser](https://github.com/nikic/PHP-Parser/releases) v4, which was released in March.

I'm using [phpstan](https://github.com/phpstan/phpstan) - `phpstan/phpstan: 0.10` requires nikic/php-parser` v4...

FWIW:

1. I cloned this repo just to see if the tests might run with the v4 but `composer update -v` didn't upgrade `nikic/php-parser` because `ocramius/code-generator-utils` uses v3.
1. I just cloned `nikic/php-parser` v4 directly into `./vendor` but the tests failed with `Class 'PhpParser\BuilderAbstract' not found`.

It might be a bit of a job.

I'll look at downgrading `phpstan` to `0.9.2` to keep going.

**Comment by pounard** [comment]
I think that nikic/php-parser causes serious dependency hell headaches.

I started using this GeneratedHydrator a while, and I can't update it in many projects because of it, it happens very often that composer dev dependencies trigger older versions to be required, causing trouble.

In the end, I do use my own fork that just write plain PHP using custom code, and which has much less dependencies.

**Comment by Ocramius** [comment]
The dependency issues will be there and are unavoidable: doesn't mean that they shouldn't be fixed.

**Comment by WyriHaximus** [comment]
Just created #81 to resolve this issue
